### ISSUE TITLE
Demo does not run with my 360 3D file

### ISSUE THREAD

**Issue by QPORIT** [vimeo/vimeo-webvr-demo#2]
I started the 360 demo. It works. I followed all the instructions (I think) to start the 360 demo on Glitch and then find my token, and then insert my file (360 3D up/down) into demo.js. The 360 demo works, but my file generates a totally black screen.

If I start the 2D demo, then find my token, and insert my file, the audio plays haltingly, but there is no video.

**Comment by caseypugh** [comment]
Sorry for the issues! I need more information in order to help you debug.
- Can you link me to your Glitch project? 
- Can you link me to your 3D 360 video on Vimeo?

**Comment by QPORIT** [comment]
Hi--


GLITCH


https://glitch.com/edit/#!/vimeo-webvr-360demo?path=public/index.html:7:58




JULY4 ON VIMEO


While the video looks quite reasonable, and expands to a full screen 360 2D video on the large screen desktop on which I am logged in to Vimeo, and on which I uploaded the video, on a different computer on which I am not logged in, the video looks bizarre, and can not go to full screen, and is incorrectly distorted.


The video is marked to be viewable by anyone; it is called July4; my user name is Eric Roffman; and the video is https://vimeo.com/256717853.




Thanks,


Eric


Eric Roffman
201 871-0950


-----Original Message-----

**Comment by caseypugh** [comment]
I found the underlying issue. There was a bug that I have now resolved, so if you remix https://vimeo-webvr-360demo.glitch.me/ this and use your own token and video, it should work.

I went ahead and took your Vimeo video and tested it myself.. here it is if you want to check it out: https://massive-particle.glitch.me/

**Comment by QPORIT** [comment]
Thanks for the help.  Definite progress.


https://massive-particle.glitch.me/ does give a 2D video in a frame which can be draqged around.  However, in Gear VR, using their webvr internet browser, it does not resolve correctly into 3D. The left and right eyes are not correct.


I wondered if the fact that July4 was not square might be the issue. I uploaded deer3ud.mp4 to Vimeo . https://vimeo.com/259419670 .  This is square up/down, but much larger than July4, 2304 x 2304 56 sec 78 MB.   I have not so far been able to get it working in the demo.



Eric




-----Original Message-----

**Comment by QPORIT** [comment]
I did some more testing. 


https://vimeo-webvr-360demo.glitch.me/ runs in 2D mode with July4.mp4  However in 3D on the GearVR Internet Browser the left and right eye images are about 90 degrees apart. (The demo video has the same problem in full-screen 3D on the Gear VR.)



deer3ud.mp4 https://vimeo.com/259419670 does not seem to run at all in the demo.  Is it too big or in the wrong format?  (I notice the thumbnail is all wrong.) 









Thanks for your help.


Eric



-----Original Message-----

**Comment by caseypugh** [comment]
@QPORIT can you try this demo again? https://massive-particle.glitch.me/

You're right, there was an issue with one of the eyes being rotated incorrectly. I have fixed the issue. Let me know if you have any more problems.

**Comment by QPORIT** [comment]
HI-


I think it works on some browsers, but not on Edge.  I'll check some more after today:




"TODAY: Invitation/Reminder: NYXR Pi-Day Meetup: “The Future ofeXtended Reality” (see www.qporit.com) including: The evolution of HMD’s (AYE!WEARE); Magic Leap One; audio conversations; $150M in venture funding from Amazon & Bose; making predictions; webXR; 3D 360VR videos on WebVR from Vimeo; the importance of Ready Player One; Pi Day; 5G; Prosumerlive VR streaming; VR videos from Unity; Deep Learning and “the scientific method”;Resource handout; and why understanding XR is fundamental for understanding thesocial issues of the future! "


Thanks,


Best,


Eric





-----Original Message-----
